# Generated by Django 4.0.4 on 2022-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
