# Generated by Django 4.0.4 on 2022-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False, help_text='select to enable this user to receive sales related stuff i.e. CTGov trials emails'),
        ),
    ]
