# Generated by Django 4.0.4 on 2022-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_alter_contacts_table_alter_ctgov1_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kw', models.CharField(max_length=36)),
                ('source', models.CharField(choices=[('desc', 'desc'), ('outcome', 'outcome')], max_length=36, null=True)),
            ],
            options={
                'verbose_name': 'Keywords',
                'verbose_name_plural': 'Keywords',
                'db_table': 'CTgovKW',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='ctgov1',
            name='action',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
