# Generated by Django 4.0.4 on 2022-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_keywords_alter_ctgov1_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgov1',
            name='action',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='ctgov1',
            name='phase',
            field=models.TextField(blank=True, max_length=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.UniqueConstraint(fields=('nct_id', 'email'), name='nct_email'),
        ),
    ]
