# Generated by Django 4.0.4 on 2022-07-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdaily', '0002_alter_mdaily_options_mdaily_imei_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdaily',
            options={'managed': True, 'verbose_name_plural': 'M+DailyMeasures'},
        ),
        migrations.AlterField(
            model_name='mdaily',
            name='org',
            field=models.ForeignKey(db_column='org', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measures_of', to='mdaily.morg'),
        ),
    ]
